### ISSUE TITLE
Score ties in run files lead to non-stable pools & evaluation

### ISSUE THREAD

**Issue by lgienapp** [joaopalotti/trectools#26] opened 2021-06-19 18:43 UTC
# Problem Description
I recently used trectools to evaluate run files which had score ties in them, i.e. multiple documents with the same score given by the retrieval system. 

Right now, when reading a run file, the documents are [sorted by score](https://github.com/joaopalotti/trectools/blob/75dcdd23bb640b6c719aa0601a00a2d2c75be0b5/trectools/trec_run.py#L45).  This leads to a problem, as the [default pandas sorting algorithm]() is quick sort, which is not stable. Therefore, the case can arise that the order of document IDs, and thus the top-X documents used in multiple places throughout trectools, is not guaranteed to be the same every time. In my case, this created the issue of a top-5 evaluation having incomplete coverage on a qrel file created from the top-5 pool of the same run files.

# Proposed Solutions
As pandas only allows unstable sorting when sorting by multiple columns, the only solution I see would be to add `rank` as third sorting axis to keep the original order in case of score ties: `self.run_data.sort_values(["query","score","rank"], inplace=True, ascending=[True,False,True])`

**Comment by joaopalotti** [comment] 2021-06-24 02:58
Hi Lukas, sorry for the late reply, and thanks for identifying this issue. Very interesting problem that you are reporting. 
Could you share with us an example of this issue happening? I wonder if we should also change the sorting functions used in trec_eval.py.

cheers

**Comment by lgienapp** [comment] 2021-06-30 10:25
I created a [mockup gist](https://gist.github.com/lgienapp/3cfd3fa4138451f175e8139105cee2e6) to illustrate the behavior. It creates dummy runs with all scores equal to 1. When creating a topX pool and subsequently evaluating at the same X depth, `.get_unjudged()` reports incomplete coverage in most cases.

**Comment by joaopalotti** [comment] 2021-08-03 18:38
Hi @lgienapp, sorry again for the huge delay to get back to you and thanks for the example, it was very useful.
Interestingly, using your suggestion did not solve the problem, I still get different coverages every time I run the code.
Alternatively, using "docid" as the tie-break solves it and aligns with the original design of `trec_eval`. 

I am going to close this issue with a small PR and feel free to re-open it in case the problem is not yet fixed or you have another suggestion! 

Thanks!

**Closed** 2021-08-03 18:38 UTC
